feedback from shams

diff --git a/kitchen/bin/test-waiter-init b/kitchen/bin/test-waiter-init
--- a/kitchen/bin/test-waiter-init
+++ b/kitchen/bin/test-waiter-init
@@ -11,11 +11,6 @@ start_test() {
     test_pid=$!
 }
 
-wait_for_script_exit() {
-    wait $test_pid
-    exit_code=$?
-}
-
 send_sigterm() {
     sleep 0.1
     kill $test_pid
@@ -30,20 +25,24 @@ end_timing() {
     elapsed_seconds=$(( $ended_at - $started_at ))
 }
 
-test_still_running() {
-    if kill -0 $test_pid &>/dev/null; then
-        still_running=true
-    else
-        still_running=false
-    fi
+failure() {
+    printf "\nFailed condition: %s\n" "$1"
+    exit 1
 }
 
 assert() {
-    if ! test "$@"; then
-        printf "\nFailed condition: %s\n" "$*"
-        exit 1
-    fi
+    test "$@" || failure "$*"
     echo -n .
+}
+
+assert_still_running() {
+    kill -0 $test_pid &>/dev/null
+    assert "RUNNING=$?" == "RUNNING=0"
+}
+
+await_exit_and_assert_code() {
+    wait $test_pid
+    assert "EXIT=$?" == "EXIT=$1"
 }
 
 #
@@ -56,8 +55,7 @@ assert() {
 start_test 'normal exit' <<EOF
 sh -c 'echo OK && exit 123'
 EOF
-wait_for_script_exit
-assert $exit_code -eq 123
+await_exit_and_assert_code 123
 assert "$(cat stdout)" == OK
 
 #
@@ -70,8 +68,7 @@ sh -c 'trap "echo Terminated; exit 1" TERM; sleep 10'
 EOF
 send_sigterm
 send_sigterm
-wait_for_script_exit
-assert $exit_code -eq 143
+await_exit_and_assert_code 143
 assert "$(cat stdout)" == Terminated
 
 #
@@ -84,12 +81,10 @@ EOF
 start_timing
 send_sigterm
 send_sigterm
-test_still_running
-assert $still_running == true
+assert_still_running
 assert "$(cat stdout)" == Delay
-wait_for_script_exit
+await_exit_and_assert_code 143
 end_timing
-assert $exit_code -eq 143
 assert "$(cat stdout)" == DelayX
 assert $elapsed_seconds -ge 2
 assert $elapsed_seconds -le 3
@@ -108,13 +103,11 @@ EOF
 send_sigterm
 sleep 1
 assert "$(cat stdout)" == Terminated
-test_still_running
-assert $still_running == true
+assert_still_running
 start_timing
 send_sigterm
-wait_for_script_exit
+await_exit_and_assert_code 143
 end_timing
-assert $exit_code -eq 143
 assert $elapsed_seconds -le 1
 
 printf '\n\nAll tests passed\n'
